author: Shinnosuke Watanabe
siteURL: http://shinnn.github.io
copyright:
  first_year: 2013

srcPath: ''
destPath: 'master/'

templatesPath: 'jade/templates/'
documentsPath: 'jade/pages/'
dataPath: 'jade/data/'

liveReloadPort: 8000
